name: Pipeline Deployment
on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions:/checkout@v3

      - name: Auth to GCP
        id: auth
        uses: google-github-actions/auth@v1
        with :
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          project_id: ${{ secrets.GCP_PROJECT_ID}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Auth Docker
        run: |
          docker login -u oauth2accesstoken -p "$(gcloud auth print-access-token)" https://asia.gcr.io

      - name: Build image
        run: |
          docker build -t asia.gcr.io/${{ secrets.GCP_PROJECT_ID}}/srikandi-app:${GITHUB_SHA::7} .

      - name: Push image
        run: |
          docker push asia.gcr.io/${{ secrets.GCP_PROJECT_ID}}/srikandi-app:${GITHUB_SHA::7}

